const CONV_SENT_ERROR = 'C_500';
const MSG_NOTFOUND = 'M_404';
const INVALID_CRED = 'L_401';
const CONNECTION_ERROR = '500';

export { CONV_SENT_ERROR, MSG_NOTFOUND, INVALID_CRED, CONNECTION_ERROR };
